### ISSUE TITLE
Wrong infohash when trying to encode larger files

### ISSUE THREAD

**Issue by FinlayDaG33k** [cj1128/deno-bencode#1]
Hii there,

I'm trying to incorporate this library in a project of mine but very quickly ran into an issue.  
You see, when I try to encode torrents with larger files, it the resulting infohash is always wrong.  

Here is an example of a working torrent.
When making an infohash for this, I get the expected value.
```js
{
  files: [
    {
      length: 144703488,
      path: [ "alpine-standard-3.14.1-x86_64.iso" ],
      "path.utf-8": [ "alpine-standard-3.14.1-x86_64.iso" ]
    },
    {
      length: 833,
      path: [ "alpine-standard-3.14.1-x86_64.iso.asc" ],
      "path.utf-8": [ "alpine-standard-3.14.1-x86_64.iso.asc" ]
    }
  ],
  name: "Alpine Linux",
  "name.utf-8": "Alpine Linux",
  "piece length": 131072,
  pieces: Uint8Array(22100) [
     51,  13, 131, 182, 239,  47, 188,  96, 141,  87,  71, 244, 104, 106,
    101, 250,   2, 133, 147, 253,  32,  40, 119,  85,  56,  57, 186, 224,
    215, 205,  40, 211,   2, 165, 237, 152,  95,  77, 129, 221,  96, 189,
     90,  49, 134,  16,  48, 208,  12,  35, 113, 248, 118,  12, 165, 110,
    137,  43, 218,  77, 186,  54, 228,  71,  34, 254, 182,  45, 180, 186,
    158,  20, 187, 137, 148,  29, 149, 146, 239, 101,  49,  70,  88,  39,
    130,  65,  41, 128, 175, 182, 204, 141, 173,  58, 132, 219, 102,  70,
    143,  19,
    ... 22000 more items
  ],
  source: "https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/x86_64/"
}
```

Here is one that _doesn't_ work:
```js
{
  files: [
    { length: 1459, path: [ "README.txt" ], "path.utf-8": [ "README.txt" ] },
    {
      length: 4389632000,
      path: [ "windows-11-22458.1000.210910-1430-en_us-amd64.iso" ],
      "path.utf-8": [ "windows-11-22458.1000.210910-1430-en_us-amd64.iso" ]
    },
    {
      length: 566,
      path: [ "windows-11-22458.1000.210910-1430-en_us-amd64.iso.sig" ],
      "path.utf-8": [ "windows-11-22458.1000.210910-1430-en_us-amd64.iso.sig" ]
    }
  ],
  name: "windows-11-22458.1000.210910-1430-en_us-amd64",
  "name.utf-8": "windows-11-22458.1000.210910-1430-en_us-amd64",
  "piece length": 4194304,
  pieces: Uint8Array(20940) [
    156,  30, 151, 158, 113, 134, 200,  72, 225, 250, 182, 255, 154, 171,
    179,   7,  80, 142,  21, 218, 201,  48, 193, 147,  91,  90, 130, 222,
    244, 138, 150, 193,   9,  40,  72, 174, 240,  78,  85, 235, 128,  15,
     51, 140,  20, 122,  48,   6,  26, 237, 155,  42,  16, 208, 155, 216,
     91,  51, 185, 115, 194, 223, 254, 229, 119,  25, 104,  34,  83, 141,
     54,  48,  87,  83, 105,  30, 130, 218, 161, 231,  95, 165, 231,  98,
    141,  94,  58,  49, 149,  11,  74,  79, 195,  27, 229, 120,  63, 184,
    204, 192,
    ... 20840 more items
  ],
  source: "https://iso-repository.finlaydag33k.nl"
}
```

Torrents with lots of smaller files, however, seem to work just fine as well.
How can I work around this?

**Comment by FinlayDaG33k** [comment]
So I've worked with the lads at the Deno Discord server and we've found out that this is caused due to big files hitting the max array size allowed in the JS spec.

**Comment by cj1128** [comment]
I am sorry but I don't quite get the problem.

`infohash` is the SHA1 hash value of the `info` section of the torrent file, you don't need to read file content to get `infohash`.

**Comment by FinlayDaG33k** [comment]
Let's assume I have 2 files:
- The Torrent file.
- The ISO (the file I'm trying to send).

When I use this library to decode the Torrent file, it runs into an issue where if the ISO file is over `2147483647`-bytes.  
This causes the `info` section of the torrent file after decoding to be truncated (due to the array size limit of JavaScript).  
So if I then I try to SHA1 hash the `info` section, it causes the hash to be "wrong" (because it misses a bunch of data).

The ISO itself (or rather, it's own file) is irrelevant, the metadata about it encoded in the torrent is.
What you can do to replicate this issue:
- Create a file that is `2147483648`-bytes long.
- Make a torrent of it.
- Import read torrent into Deno.
```ts
const content = Deno.readFile('whatever.torrent');
```
- Decode torrent using this library.
```ts
import { decode } from "https://deno.land/x/bencode@v0.1.2/mod.ts";
const decoded = decode(content);
```
- SHA1 hash the `info` section.
```ts
import { createHash } from "https://deno.land/std@0.107.0/hash/mod.ts";
const hash = createHash("sha1");
hash.update(decoded.info);
console.log(hash.toString()); // Will show the wrong infohash
```

**Comment by cj1128** [comment]
Thank you for the detailed explanation.

The problem is not the array size limit but the buggy `num >> 0` in the `encodeNum` function.

JS engine performs bit operations as 32-bit signed integer, so `2500000000 >> 0` returns `-1794967296` and this is clearly incorrect.

Check out the latest v0.1.3 version.

**Comment by FinlayDaG33k** [comment]
I can confirm this fixes the issue, thanks :)
